package pacote_menus;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;

public class MenuCamposGerais extends javax.swing.JFrame {

	/**
	 * Creates new form MenuInicial
	 */
	public MenuCamposGerais() {
		initComponents();
		setTitle("Campos Gerais");
		setIconBar();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		guarapuava = new javax.swing.JButton();
		irati = new javax.swing.JButton();
		jaguariaiva = new javax.swing.JButton();
		pgSenai = new javax.swing.JButton();
		pgSesi = new javax.swing.JButton();
		teleSenai = new javax.swing.JButton();
		teleSesi = new javax.swing.JButton();
		uniaoVitoria = new javax.swing.JButton();
		saoMateus = new javax.swing.JButton();
		retornar = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JSeparator();

		jLabel2.setText("Escolha a  Região");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jLabel1.setText("Região de Campos Gerais");

		guarapuava.setText("Guarapuava");
		guarapuava.setFocusPainted(false);
		guarapuava.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				guarapuavaActionPerformed(evt);
			}
		});

		irati.setText("Iratí");
		irati.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				iratiActionPerformed(evt);
			}
		});

		jaguariaiva.setText("Jaguariaíva");
		jaguariaiva.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jaguariaivaActionPerformed(evt);
			}
		});

		pgSenai.setText("<html>Ponta Grossa<br>Senai</html>");
		pgSenai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pgSenaiActionPerformed(evt);
			}
		});

		pgSesi.setText("<html>Ponta Grossa<br>Senai</html>");
		pgSesi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pgSesiActionPerformed(evt);
			}
		});

		teleSenai.setText("<html>Telêmaco<br>Senai</html>");
		teleSenai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				teleSenaiActionPerformed(evt);
			}
		});

		teleSesi.setText("<html>Telêmaco<br>Sesi</html>");
		teleSesi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				teleSesiActionPerformed(evt);
			}
		});

		uniaoVitoria.setText("<html>União da<br>Vitoria</html>");
		uniaoVitoria.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uniaoVitoriaActionPerformed(evt);
			}
		});

		saoMateus.setText("<html>São Mateus<br>do Sul</html>");
		saoMateus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saoMateusActionPerformed(evt);
			}
		});

		retornar.setBackground(new java.awt.Color(152, 143, 143));
		retornar.setText("Retornar");
		retornar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				retornarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pgSenai, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(teleSenai, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(pgSesi, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(teleSesi, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(retornar, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup()
										.addComponent(guarapuava, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(irati, javax.swing.GroupLayout.PREFERRED_SIZE,
												110, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(saoMateus, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jaguariaiva, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(uniaoVitoria, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jSeparator1).addComponent(jSeparator2))
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(84, 84, 84)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24).addComponent(jLabel1).addGap(28, 28, 28)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(guarapuava, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(irati, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jaguariaiva, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(4, 4, 4)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(pgSenai, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(pgSesi, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(saoMateus, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(teleSenai, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(teleSesi, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(uniaoVitoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
						.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(retornar,
								javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void guarapuavaActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\servergpv04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void iratiActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serverirtss04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void retornarActionPerformed(java.awt.event.ActionEvent evt) {
		new MenuLocalizacao().setVisible(true);
		dispose();
	}

	private void jaguariaivaActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serverjgvsn04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void pgSenaiActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serverpgrsn04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void pgSesiActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serverpgrss04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void saoMateusActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serversmsss04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void teleSenaiActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\servertmbsn04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void teleSesiActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\servertmbss04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void uniaoVitoriaActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Runtime.getRuntime().exec("explorer \\\\serveruvt04");
		} catch (IOException ex) {
			Logger.getLogger(MenuCamposGerais.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuCamposGerais.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuCamposGerais.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuCamposGerais.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuCamposGerais.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuCamposGerais().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton guarapuava;
	private javax.swing.JButton irati;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JButton jaguariaiva;
	private javax.swing.JButton pgSenai;
	private javax.swing.JButton pgSesi;
	private javax.swing.JButton retornar;
	private javax.swing.JButton saoMateus;
	private javax.swing.JButton teleSenai;
	private javax.swing.JButton teleSesi;
	private javax.swing.JButton uniaoVitoria;
	// End of variables declaration

	private void setIconBar() {
		ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("printer.png"));
    	
    	setIconImage(icon.getImage());
	}
}
